#!/usr/bin/env python3
"""snip

Usage:
  snip <snippet>
  snip <snippet> -c <context>

Examples:
  snip helloworld -c "name=World;"


Options:
  -c --context context for the snippet
"""

from snippyt import *
from docopt import docopt


if __name__ == "__main__":
    mgr = Snippyt()
    options = docopt(__doc__, version='snippyt 0.0.1')
    context_dict = {}
    path = options['<snippet>']

    if options['--context']:
        context = options['--context']
        context = filter(lambda x: x is not None, context.split(';'))
        for kv in context:
            k, v = kv.split('=')
            context_dict[k] = v

    ret = mgr.run(path=path, context=context_dict)
    print(ret)
